apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  loadBalancerIP: 10.64.35.187
  selector:
    app: mariadb
  ports:
  - name: mariadb
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer
