---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  annotations:
    hpe.com/description: "My volume to be transitioned"
    hpe.com/perfPolicy: "SQL Server"
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 16Gi
  storageClassName: hpe-transition
