Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "kubecon"
  config.vm.network "private_network", ip: "192.168.59.40"
  config.vm.provider "vmware_fusion" do |vmf|
     vmf.cpus = "2"
     vmf.memory = "3192"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "kubecon.yml"
    ansible.extra_vars = {
      local_listener: "192.168.59.40" 
    }
  end
end
