---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: database
provisioner: hpe.com/nimble
parameters:
  description: "Volume provisioned from database StorageClass"
  fsMode: "0770"
  protectionTemplate: General
  perfPolicy: MariaDB
  folder: Uncapped
