---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
    - name: mariadb
      port: 3306
  selector:
    app: mariadb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: bitnami/mariadb
          name: mariadb
          env:
            - name: MARIADB_USER
              value: bn_wordpress
            - name: MARIADB_DATABASE
              value: bitnami_wordpress
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb
              mountPath: /bitnami
      volumes:
        - name: mariadb
          persistentVolumeClaim: 
            claimName: mariadb
