---
apiVersion: v1
kind: Secret
metadata:
  name: datagen
data:
  password: WU9VUl9QQVNTV09SRA==
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datagen
  labels:
    app: datagen
    db: dgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datagen
      db: dgdb
  template:
    metadata:
      labels:
        app: datagen
        db: dgdb
    spec:
      containers:
        - image: mariadb:latest
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datagen
                  key: password
            - name: MYSQL_DATABASE
              value: datagen 
            - name: MYSQL_USER
              value: datagen 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datagen
                  key: password
          ports:
            - containerPort: 3306
              name: dgdb
        - image: mvisonneau/generatedata
          name: datagen
          env:
            - name: GD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datagen
                  key: password
            - name: GD_DB_HOSTNAME
              value: dgdb
            - name: GD_DB_NAME
              value: datagen
            - name: GD_DB_USERNAME
              value: datagen
          ports:
            - containerPort: 80
              name: datagen
---
apiVersion: v1
kind: Service
metadata:
  name: dgdb
spec:
  selector:
    db: dgdb
  ports:
  - name: dgdb
    protocol: TCP
    port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: datagen
spec:
  selector:
    app: datagen
  ports:
  - name: datagen
    port: 80
