version: "3.3"
services:
  api:
    container_name: "api"
    build: 
      context: "app/"
      args:
        BUILD_NUMBER: ${BUILD_NUMBER:-unknown}
    image: "drajen/populous:${BUILD_NUMBER:-unknown}"
    ports:
      - "8000:8000"
    environment:
      POPULOUS_USER: populous
      POPULOUS_PASSWORD: YOUR_PASSWORD
      POPULOUS_HOST: pldb
      POPULOUS_DB: populous
  pldb:
    image: "drajen/pldb"
    volumes:
      - type: volume
        source: cloneofprod
        target: /var/lib/mysql
        volume:
          nocopy: true
volumes:
  cloneofprod:
    external: 
      name: cloneofprod-${BUILD_NUMBER:-unknown}
