---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pldb
  annotations:
    volume.beta.kubernetes.io/storage-class: cloneofprod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
