---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: transactionaldb
provisioner: hpe.com/nimble
parameters:
  description: "Volume provisioned by HPE Nimble Storage Kube Storage Controller from transactionaldb StorageClass"
  protectionTemplate: General
  perfPolicy: "SQL Server"
  fsMode: "0770"
