---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-clone
  annotations:
    csi.hpe.com/performancePolicy: "Windows File Server"
    csi.hpe.com/limitIops: "5000"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  dataSource:
    name: wordpress-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
