---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-clone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: hpe-database
  dataSource:
    name: mariadb-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
