---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: mariadb-snapshot
spec:
  source:
    name: mariadb
    kind: PersistentVolumeClaim
  snapshotClassName: hpe-snapshot
