---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: wordpress-snapshot
spec:
  source:
    name: wordpress
    kind: PersistentVolumeClaim
  snapshotClassName: hpe-snapshot
