---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-clone
  name: wordpress-clone
spec:
  type: LoadBalancer
  ports:
    - name: wordpress-clone
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress-clone
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-clone
spec:
  rules:
  - host: wp-clone.dev.datamattsson.io
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress-clone
          servicePort: wordpress-clone
