---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  type: LoadBalancer
  ports:
    - name: wordpress
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
spec:
  rules:
  - host: wp.dev.datamattsson.io
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: wordpress
