version: "3"
services:
  web:
    image: nginx:1.14
    ports:
    - "8080:80"
    volumes:
    - html:/usr/share/nginx/html
volumes:
  html:
    driver: hpecv
    driver_opts:
      sizeInGiB: "8"
      limitIOPS: "2000"
      volumeType: GPF
