---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-clone
  labels:
    app: mariadb-clone
spec:
  containers:
    - image: mariadb:latest
      name: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: YOUR_PASSWORD
      ports:
        - containerPort: 3306
          name: mariadb
      volumeMounts:
        - name: mariadb
          mountPath: /var/lib/mysql
  volumes:
    - name: mariadb
      persistentVolumeClaim: 
        claimName: mariadb-clone
