---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: transactionaldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
