---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: general
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: hpe.com/cv
parameters:
  description: "Volume provisioned by HPE Nimble Storage Kube Storage Controller from default StorageClass"
