---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-clone
  annotations:
    hpe.com/cloneOfPVC: mariadb
    hpe.com/limitIOPS: "1000"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: database
