---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-clone
  name: wordpress-clone
spec:
  type: LoadBalancer
  ports:
    - name: wordpress
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress-clone
