apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: ioping
    image: hpestorage/ioping
    command: [ "ioping" ]
    args: [ "/data" ]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc
