---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    manual: nfs
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - vers=4.1
  nfs:
    path: /export
    server: 10.110.69.26
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      manual: nfs
---
apiVersion: v1
kind: Pod
metadata:
  name: ioping
spec:
  containers:
  - name: ioping
    image: hpestorage/ioping
    command: [ "ioping" ]
    args: [ "/nfs" ]
    volumeMounts:
    - name: nfs
      mountPath: /nfs
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: pvc-nfs
