---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-clone
  annotations:
    hpe.com/cloneOfPVC: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
