---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  annotations:
    hpe.com/perfPolicy: "Windows File Server"
    hpe.com/limitIOPS: "5000"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
