---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - image: bash
          name: proxy
          args:
            - sleep
            - 128d
