---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-remote
  labels:
    app: proxy-remote
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: proxy-remote
  template:
    metadata:
      labels:
        app: proxy-remote
    spec:
      containers:
        - image: bash
          name: proxy
          args:
            - sleep
            - 64d
      nodeSelector:
        site: remote
      tolerations:
      - key: "node.kubernetes.io/unschedulable"
        operator: "Exists"
        effect: "NoSchedule"
