---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: override
  annotations:
    hpe.com/perfPolicy: "Windows File Server"
    hpe.com/description: "My overridden description"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
  storageClassName: override
