---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: general
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: hpe.com/nimble
parameters:
  allowOverrides: description,perfPolicy,importVol,snapshot,restore,destroyOnRm
  destroyOnRm: "false"
  description: "Volume provisioned from default StorageClass"
  fsMode: "0770"
  protectionTemplate: General
  perfPolicy: General
  folder: General
