---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sidecar
  labels:
    app: sidecar
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: sidecar
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
        - image: bash
          name: sidecar
          args:
            - sleep
            - 128d
