---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpe-view-storageclasses
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpe-view-storageclasses
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpe-view-storageclasses
subjects:
- kind: Group
  name: system:authenticated
